export const DEFAULT_TYPE  = {
    CONFERENCE_FOLLOWED : 'CONFERENCE_FOLLOWED',
    CONFERENCE_UNFOLLOWED : 'CONFERENCE_UNFOLLOWED',
    CONFERENCE_CALENDAR_ADDED : 'CONFERENCE_CALENDAR_ADDED',
    CONFERENCE_CALENDAR_REMOVED : 'CONFERENCE_CALENDAR_REMOVED',
    CONFERENCE_BLACKLISTED : 'CONFERENCE_BLACKLISTED',
    CONFERENCE_UNBLACKLISTED : 'CONFERENCE_UNBLACKLISTED',
} as const