export const DEFAULT_TYPE  = {
    CONFERENCE_FOLLOWED : 'CONFERENCE_FOLLOWED',
    CONFERENCE_UNFOLLOWED : 'CONFERENCE_UNFOLLOWED',
    CONFERENCE_CALENDAR_ADDED : 'CONFERENCE_CALENDAR_ADDED',
    CONFERENCE_CALENDAR_REMOVED : 'CONFERENCE_CALENDAR_REMOVED',
    CONFERENCE_BLACKLISTED : 'CONFERENCE_BLACKLISTED',
    CONFERENCE_UNBLACKLISTED : 'CONFERENCE_UNBLACKLISTED',
    ON_NOTIFICATION : 'ON_NOTIFICATION',
    UP_COMING_CONFERENCE : 'UP_COMING_CONFERENCE',
    SEND_THROUGH_EMAIL : 'SEND_THROUGH_EMAIL',
    CONFERENCE_UPDATED : 'CONFERENCE_UPDATED',
    PROFILE_UPDATED : 'PROFILE_UPDATED',

} as const